/*
Bandwidth

Testing PhoneNumberLookupAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	openapiclient "github.com/winking324/bandwidth"
)

func Test_openapi_PhoneNumberLookupAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PhoneNumberLookupAPIService CreateLookup", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var accountId string

		resp, httpRes, err := apiClient.PhoneNumberLookupAPI.CreateLookup(context.Background(), accountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PhoneNumberLookupAPIService GetLookupStatus", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var accountId string
		var requestId string

		resp, httpRes, err := apiClient.PhoneNumberLookupAPI.GetLookupStatus(context.Background(), accountId, requestId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
