/*
Bandwidth

Bandwidth's Communication APIs

API version: 1.0.0
Contact: letstalk@bandwidth.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)




// MfaUnauthorizedRequestError struct for MfaUnauthorizedRequestError
type MfaUnauthorizedRequestError struct {
	// Unauthorized
	Message *string `json:"message,omitempty"`
}

// NewMfaUnauthorizedRequestError instantiates a new MfaUnauthorizedRequestError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMfaUnauthorizedRequestError() *MfaUnauthorizedRequestError {
	this := MfaUnauthorizedRequestError{}
	return &this
}

// NewMfaUnauthorizedRequestErrorWithDefaults instantiates a new MfaUnauthorizedRequestError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMfaUnauthorizedRequestErrorWithDefaults() *MfaUnauthorizedRequestError {
	this := MfaUnauthorizedRequestError{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *MfaUnauthorizedRequestError) GetMessage() string {
	if o == nil || utils.IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MfaUnauthorizedRequestError) GetMessageOk() (*string, bool) {
	if o == nil || utils.IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *MfaUnauthorizedRequestError) HasMessage() bool {
	if o != nil && !utils.IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *MfaUnauthorizedRequestError) SetMessage(v string) {
	o.Message = &v
}

func (o MfaUnauthorizedRequestError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MfaUnauthorizedRequestError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableMfaUnauthorizedRequestError struct {
	value *MfaUnauthorizedRequestError
	isSet bool
}

func (v NullableMfaUnauthorizedRequestError) Get() *MfaUnauthorizedRequestError {
	return v.value
}

func (v *NullableMfaUnauthorizedRequestError) Set(val *MfaUnauthorizedRequestError) {
	v.value = val
	v.isSet = true
}

func (v NullableMfaUnauthorizedRequestError) IsSet() bool {
	return v.isSet
}

func (v *NullableMfaUnauthorizedRequestError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMfaUnauthorizedRequestError(val *MfaUnauthorizedRequestError) *NullableMfaUnauthorizedRequestError {
	return &NullableMfaUnauthorizedRequestError{value: val, isSet: true}
}

func (v NullableMfaUnauthorizedRequestError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMfaUnauthorizedRequestError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


