/*
Bandwidth

Bandwidth's Communication APIs

API version: 1.0.0
Contact: letstalk@bandwidth.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)




// MfaRequestError struct for MfaRequestError
type MfaRequestError struct {
	// A message describing the error with your request.
	Error *string `json:"error,omitempty"`
	// The associated requestId from AWS.
	RequestId *string `json:"requestId,omitempty"`
}

// NewMfaRequestError instantiates a new MfaRequestError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMfaRequestError() *MfaRequestError {
	this := MfaRequestError{}
	return &this
}

// NewMfaRequestErrorWithDefaults instantiates a new MfaRequestError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMfaRequestErrorWithDefaults() *MfaRequestError {
	this := MfaRequestError{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *MfaRequestError) GetError() string {
	if o == nil || utils.IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MfaRequestError) GetErrorOk() (*string, bool) {
	if o == nil || utils.IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *MfaRequestError) HasError() bool {
	if o != nil && !utils.IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *MfaRequestError) SetError(v string) {
	o.Error = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *MfaRequestError) GetRequestId() string {
	if o == nil || utils.IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MfaRequestError) GetRequestIdOk() (*string, bool) {
	if o == nil || utils.IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *MfaRequestError) HasRequestId() bool {
	if o != nil && !utils.IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *MfaRequestError) SetRequestId(v string) {
	o.RequestId = &v
}

func (o MfaRequestError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MfaRequestError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !utils.IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}
	return toSerialize, nil
}

type NullableMfaRequestError struct {
	value *MfaRequestError
	isSet bool
}

func (v NullableMfaRequestError) Get() *MfaRequestError {
	return v.value
}

func (v *NullableMfaRequestError) Set(val *MfaRequestError) {
	v.value = val
	v.isSet = true
}

func (v NullableMfaRequestError) IsSet() bool {
	return v.isSet
}

func (v *NullableMfaRequestError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMfaRequestError(val *MfaRequestError) *NullableMfaRequestError {
	return &NullableMfaRequestError{value: val, isSet: true}
}

func (v NullableMfaRequestError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMfaRequestError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


