/*
Bandwidth

Bandwidth's Communication APIs

API version: 1.0.0
Contact: letstalk@bandwidth.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)




// MfaForbiddenRequestError struct for MfaForbiddenRequestError
type MfaForbiddenRequestError struct {
	// The message containing the reason behind the request being forbidden.
	Message *string `json:"message,omitempty"`
}

// NewMfaForbiddenRequestError instantiates a new MfaForbiddenRequestError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMfaForbiddenRequestError() *MfaForbiddenRequestError {
	this := MfaForbiddenRequestError{}
	return &this
}

// NewMfaForbiddenRequestErrorWithDefaults instantiates a new MfaForbiddenRequestError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMfaForbiddenRequestErrorWithDefaults() *MfaForbiddenRequestError {
	this := MfaForbiddenRequestError{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *MfaForbiddenRequestError) GetMessage() string {
	if o == nil || utils.IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MfaForbiddenRequestError) GetMessageOk() (*string, bool) {
	if o == nil || utils.IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *MfaForbiddenRequestError) HasMessage() bool {
	if o != nil && !utils.IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *MfaForbiddenRequestError) SetMessage(v string) {
	o.Message = &v
}

func (o MfaForbiddenRequestError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MfaForbiddenRequestError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !utils.IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableMfaForbiddenRequestError struct {
	value *MfaForbiddenRequestError
	isSet bool
}

func (v NullableMfaForbiddenRequestError) Get() *MfaForbiddenRequestError {
	return v.value
}

func (v *NullableMfaForbiddenRequestError) Set(val *MfaForbiddenRequestError) {
	v.value = val
	v.isSet = true
}

func (v NullableMfaForbiddenRequestError) IsSet() bool {
	return v.isSet
}

func (v *NullableMfaForbiddenRequestError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMfaForbiddenRequestError(val *MfaForbiddenRequestError) *NullableMfaForbiddenRequestError {
	return &NullableMfaForbiddenRequestError{value: val, isSet: true}
}

func (v NullableMfaForbiddenRequestError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMfaForbiddenRequestError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


